### PR TITLE
Render all strings with single quotes

### PR DESCRIPTION
**Pull request by jjoos**
When I was working on https://github.com/clutchski/coffeelint/pull/346, I noticed that there were a lot of unneeded double quotes in the output. Since they have a special meaning in coffee script this could also mean unintended string interpolation.

I probably missed some edge cases, so please take a good look before merging!

### CODE REVIEW

**Comment by clayallsopp** [comment]
+1, would love it for that same reason (coffeelint)

**Comment by rylanc** [comment]
+1. Now that coffeelint supports transforms, this would be very helpful. Single quotes should be the default considering there are no rules forbidding them, while the `no_unnecessary_double_quotes` forbids double quotes.

**Comment by chriswynnyk** [comment]
+1, this would be great.  Are there any specific concerns blocking this PR from being merged?  Thanks!

**Comment by PhilVargas** [comment]
+1 . any updates? the merge conflict looks like it just from the test output text

**Comment by firstdoit** [comment]
Apparently this is not going to happen? :/

**Comment by jjoos** [comment]
We migrated away from coffeescript, so closing this PR. Feel free to copy/rebase the code and create your own pull request.

**Pull request closed without merging**
